import nodemailer from 'nodemailer';//used to send the emails from the nodejs
import { config } from 'dotenv';
config()//call
export const verifyEmail=(token,email)=>{

  const transporter=nodemailer.createTransport({
    service:'gmail',
    auth:{
        user:process.env.MAIL_USER,
        pass:process.env.MAIL_PASS//app password generated by google for node app 16 digit
    }
  })//transport ( Connects your app to email service (Gmail))

  const emailConfigurations={
    //sender email
    from:process.env.MAIL_USER,
    //user email
    to:email,
    //subject
    subject:'Email Verification..',
    //text of email body
    text:`Hi There ,You have recently visited our website and entered your email.Please follow the given link to verify your email http://localhost:5173/verify/${token}`
  }//emailConfiguartion  👉 Object that defines email content

  transporter.sendMail(emailConfigurations,(err,info)=>{
    if(err)
    {
        throw new Error(err);
    }
    console.log("Email Sent Successfully");
    // console.log(info);
  })//this is the main function (actually send the mail)

}//verify Email

